on: 
  schedule:
  - cron: 0 2 * * *
name: Daily Collection
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: NPM Build
      uses: actions/npm@master
      with:
        args: install
    - name: Collect Go Metrics 
      uses: actions/npm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: node
        args: cli.js repo-search go --output=logs
    - name: Collect JS Metrics 
      uses: actions/npm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: node
        args: cli.js repo-search javascript --output=logs
    - name: Collect Google Trends 
      uses: actions/npm@master
      with:
        entrypoint: node
        args: cli.js trends --output=logs
    - name: Re-write README
      uses: actions/npm@master
      with:
        entrypoint: node
        args: cli.js readme
    - name: Publish Logs to Repo
      uses: mikeal/publish-to-github-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
