on: "schedule(* * * * *)"
name: Build and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Run Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Run
      uses: actions/npm@master
      env:
        GOOGLE_CREDENTIAL_B64: ${{ secrets.GOOGLE_CREDENTIAL_B64 }}
      with:
        entrypoint: node
        args: cli.js go --output=logs
    - name: Git Add
      uses: actions/npm@master
      with:
        entrypoint: git
        args: add logs
    - name: Git Commit
      uses: actions/npm@master
      with:
        entrypoint: git
        args: 'commit -m "log: publish"'
    - name: Git Push
      uses: actions/npm@master
      with:
        entrypoint: git
        args: push origin master
